language: php

dist: xenial

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION=2.x-dev

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL MFA_VERSION=4.0.x-dev PHPUNIT_COVERAGE_TEST=1

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-cms:^4
  - if [[ $MFA_VERSION ]]; then composer require --no-update silverstripe/mfa:"$MFA_VERSION"; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:

  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml --bootstrap=vendor/silverstripe/cms/tests/bootstrap.php; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs code/ tests/ *.php; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
