name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: emteknetnz/gha-ci/.github/workflows/ci.yml@main
    with:
      extra_jobs: |
        - composer_require_extra: silverstripe/mfa:^4
          name_suffix: 'mfa'
          phpunit: true
        - composer_require_extra: silverstripe/session-manager:^1
          name_suffix: 'session-manager'
          phpunit: true
